export interface CountryOption {
  value: string;
  label: string;
}

// ISO 3166-1 alpha-2 country options for registration flows.
export const ISO_COUNTRY_OPTIONS: CountryOption[] = [
  { value: 'AE', label: 'United Arab Emirates (AE)' },
  { value: 'AR', label: 'Argentina (AR)' },
  { value: 'AT', label: 'Austria (AT)' },
  { value: 'AU', label: 'Australia (AU)' },
  { value: 'BE', label: 'Belgium (BE)' },
  { value: 'BG', label: 'Bulgaria (BG)' },
  { value: 'BH', label: 'Bahrain (BH)' },
  { value: 'BR', label: 'Brazil (BR)' },
  { value: 'CA', label: 'Canada (CA)' },
  { value: 'CH', label: 'Switzerland (CH)' },
  { value: 'CI', label: "Cote d'Ivoire (CI)" },
  { value: 'CL', label: 'Chile (CL)' },
  { value: 'CM', label: 'Cameroon (CM)' },
  { value: 'CN', label: 'China (CN)' },
  { value: 'CO', label: 'Colombia (CO)' },
  { value: 'CR', label: 'Costa Rica (CR)' },
  { value: 'CY', label: 'Cyprus (CY)' },
  { value: 'CZ', label: 'Czech Republic (CZ)' },
  { value: 'DE', label: 'Germany (DE)' },
  { value: 'DK', label: 'Denmark (DK)' },
  { value: 'DO', label: 'Dominican Republic (DO)' },
  { value: 'DZ', label: 'Algeria (DZ)' },
  { value: 'EC', label: 'Ecuador (EC)' },
  { value: 'EE', label: 'Estonia (EE)' },
  { value: 'EG', label: 'Egypt (EG)' },
  { value: 'ES', label: 'Spain (ES)' },
  { value: 'ET', label: 'Ethiopia (ET)' },
  { value: 'FI', label: 'Finland (FI)' },
  { value: 'FR', label: 'France (FR)' },
  { value: 'GB', label: 'United Kingdom (GB)' },
  { value: 'GH', label: 'Ghana (GH)' },
  { value: 'GR', label: 'Greece (GR)' },
  { value: 'HK', label: 'Hong Kong (HK)' },
  { value: 'HR', label: 'Croatia (HR)' },
  { value: 'HU', label: 'Hungary (HU)' },
  { value: 'ID', label: 'Indonesia (ID)' },
  { value: 'IE', label: 'Ireland (IE)' },
  { value: 'IL', label: 'Israel (IL)' },
  { value: 'IN', label: 'India (IN)' },
  { value: 'IT', label: 'Italy (IT)' },
  { value: 'JM', label: 'Jamaica (JM)' },
  { value: 'JO', label: 'Jordan (JO)' },
  { value: 'JP', label: 'Japan (JP)' },
  { value: 'KE', label: 'Kenya (KE)' },
  { value: 'KR', label: 'South Korea (KR)' },
  { value: 'KW', label: 'Kuwait (KW)' },
  { value: 'KZ', label: 'Kazakhstan (KZ)' },
  { value: 'LB', label: 'Lebanon (LB)' },
  { value: 'LK', label: 'Sri Lanka (LK)' },
  { value: 'LT', label: 'Lithuania (LT)' },
  { value: 'LU', label: 'Luxembourg (LU)' },
  { value: 'LV', label: 'Latvia (LV)' },
  { value: 'MA', label: 'Morocco (MA)' },
  { value: 'MT', label: 'Malta (MT)' },
  { value: 'MU', label: 'Mauritius (MU)' },
  { value: 'MX', label: 'Mexico (MX)' },
  { value: 'MY', label: 'Malaysia (MY)' },
  { value: 'NG', label: 'Nigeria (NG)' },
  { value: 'NL', label: 'Netherlands (NL)' },
  { value: 'NO', label: 'Norway (NO)' },
  { value: 'NZ', label: 'New Zealand (NZ)' },
  { value: 'OM', label: 'Oman (OM)' },
  { value: 'PA', label: 'Panama (PA)' },
  { value: 'PE', label: 'Peru (PE)' },
  { value: 'PH', label: 'Philippines (PH)' },
  { value: 'PK', label: 'Pakistan (PK)' },
  { value: 'PL', label: 'Poland (PL)' },
  { value: 'PT', label: 'Portugal (PT)' },
  { value: 'QA', label: 'Qatar (QA)' },
  { value: 'RO', label: 'Romania (RO)' },
  { value: 'RS', label: 'Serbia (RS)' },
  { value: 'RU', label: 'Russia (RU)' },
  { value: 'RW', label: 'Rwanda (RW)' },
  { value: 'SA', label: 'Saudi Arabia (SA)' },
  { value: 'SE', label: 'Sweden (SE)' },
  { value: 'SG', label: 'Singapore (SG)' },
  { value: 'SI', label: 'Slovenia (SI)' },
  { value: 'SK', label: 'Slovakia (SK)' },
  { value: 'SN', label: 'Senegal (SN)' },
  { value: 'TH', label: 'Thailand (TH)' },
  { value: 'TN', label: 'Tunisia (TN)' },
  { value: 'TR', label: 'Turkey (TR)' },
  { value: 'TW', label: 'Taiwan (TW)' },
  { value: 'TZ', label: 'Tanzania (TZ)' },
  { value: 'UA', label: 'Ukraine (UA)' },
  { value: 'UG', label: 'Uganda (UG)' },
  { value: 'US', label: 'United States (US)' },
  { value: 'UY', label: 'Uruguay (UY)' },
  { value: 'VN', label: 'Vietnam (VN)' },
  { value: 'ZA', label: 'South Africa (ZA)' },
  { value: 'ZM', label: 'Zambia (ZM)' },
  { value: 'ZW', label: 'Zimbabwe (ZW)' },
];
